# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2AhxH2oOANEvgJy4bnhIhl1kegwGkmu

Usando el dataset de Iris, basado en el largo y ancho de los pétalos. Crear 5 puntos nuevos y clasificarlos con KNN.
"""

from google.colab import files
archivo_subido = files.upload()

import zipfile

with zipfile.ZipFile("iris.zip", 'r') as zip_ref:
    zip_ref.extractall(".")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

nombres_columnas = ["longitud_sepalo", "ancho_sepalo",
                    "longitud_petalo", "ancho_petalo", "clase"]

iris_df = pd.read_csv("bezdekIris.data", header=None, names=nombres_columnas)


X = iris_df[["longitud_petalo", "ancho_petalo"]].values
y = iris_df["clase"].values


X_entrenar, X_prueba, y_entrenar, y_prueba = train_test_split(
    X, y, test_size=0.2, random_state=42
)


knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_entrenar, y_entrenar)


nuevos_puntos = np.array([
    [1.5, 0.3],
    [4.5, 1.5],
    [5.1, 2.0],
    [6.0, 2.5],
    [3.5, 1.0]
])


predicciones = knn.predict(nuevos_puntos)


resultado = pd.DataFrame(nuevos_puntos, columns=["longitud_petalo", "ancho_petalo"])
resultado["clase_predicha"] = predicciones
print(resultado.to_string(index=False))