# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Rf4ZGB2TRIThCqrJTGZxkczkGSmp-tA

Las clasificaciones de velocidad y agilidad para 20 atletas fueron registradas así como si fueron reclutados por un equipo profesional.

Predecir si el ID 21 fue o no jugador profesional usando KNN.
"""

import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

data = {
    "ID": range(1, 21),
    "Velocidad": [2.50, 3.75, 2.25, 3.25, 2.75, 4.50, 3.50, 3.00, 4.00, 4.25,
                  2.00, 5.00, 8.25, 5.75, 4.75, 5.50, 5.25, 7.00, 7.50, 7.25],
    "Agilidad": [6.00, 8.00, 5.50, 8.25, 7.50, 5.00, 5.25, 3.25, 4.00, 3.75,
                 2.00, 2.50, 8.50, 8.75, 6.25, 6.75, 9.50, 4.25, 8.00, 5.75],
    "Profesional": ["no","no","no","no","no","no","no","no","no","no",
                    "no","no","yes","yes","yes","yes","yes","yes","yes","yes"]
}

df = pd.DataFrame(data)

X = df[["Velocidad", "Agilidad"]].values
y = df["Profesional"].values


knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y)


nuevo = np.array([[6.75, 3.00]])


prediccion = knn.predict(nuevo)
print("¿Jugador profesional ID 21?:", prediccion[0])